# Generated by Django 3.1.5 on 2021-05-06 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_auto_20210506_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('asset', models.ManyToManyField(to='assets.Assets', verbose_name='资产')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
