# Generated by Django 3.1.5 on 2021-05-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='username',
            field=models.CharField(max_length=20, verbose_name='管理用户名'),
        ),
    ]
